namespace TheMaxLab.SqlServerDiagnostics.App.Forms
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.MenuStrip mainMenu;
        private System.Windows.Forms.ToolStripMenuItem connectMenuItem, changeConnectionMenuItem, disconnectMenuItem, runSelectedMenuItem, runHealthCheckMenuItem, cancelMenuItem, refreshMenuItem, clearResultsMenuItem, aboutMenuItem;
        private System.Windows.Forms.ToolStrip toolStrip;
        private System.Windows.Forms.ToolStripButton connectToolButton, runToolButton, healthToolButton, cancelToolButton;
        private System.Windows.Forms.Panel contextPanel, explorerHost, detailsPanel, resultHost, healthHeaderPanel, healthResultHost;
        private System.Windows.Forms.Label connectionStateLabel, serverValueLabel, versionValueLabel, diagnosticNameLabel, healthSummaryLabel;
        private System.Windows.Forms.ComboBox databaseComboBox;
        private System.Windows.Forms.Button refreshButton, allButton, performanceButton, indexesButton, integrityButton, schemaButton, healthCheckButton, viewSqlButton, runDiagnosticButton;
        private System.Windows.Forms.SplitContainer workspaceSplit, diagnosticsSplit, detailSplit;
        private System.Windows.Forms.FlowLayoutPanel navigationPanel;
        private System.Windows.Forms.TabControl workspaceTabs;
        private System.Windows.Forms.TabPage diagnosticsTab, healthCheckTab;
        private System.Windows.Forms.TextBox diagnosticDescriptionTextBox;
        private System.Windows.Forms.TableLayoutPanel metadataTable;
        private System.Windows.Forms.ProgressBar healthProgressBar;
        private System.Windows.Forms.DataGridView healthGrid;
        private System.Windows.Forms.StatusStrip statusStrip;
        private System.Windows.Forms.ToolStripStatusLabel connectionStatusLabel, diagnosticStatusLabel, operationStatusLabel, durationStatusLabel;
        private System.Windows.Forms.ToolStripProgressBar operationProgressBar;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container(); SuspendLayout();
            mainMenu = new System.Windows.Forms.MenuStrip(); var connectionMenu = new System.Windows.Forms.ToolStripMenuItem("&Connection"); connectMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Connect..."); changeConnectionMenuItem = new System.Windows.Forms.ToolStripMenuItem("C&hange Connection..."); disconnectMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Disconnect"); connectionMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { connectMenuItem, changeConnectionMenuItem, disconnectMenuItem }); var diagnosticsMenu = new System.Windows.Forms.ToolStripMenuItem("&Diagnostics"); runSelectedMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Run Selected"); runHealthCheckMenuItem = new System.Windows.Forms.ToolStripMenuItem("Run &Health Check"); cancelMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Cancel"); diagnosticsMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { runSelectedMenuItem, runHealthCheckMenuItem, cancelMenuItem }); var viewMenu = new System.Windows.Forms.ToolStripMenuItem("&View"); refreshMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Refresh"); clearResultsMenuItem = new System.Windows.Forms.ToolStripMenuItem("&Clear Results"); viewMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { refreshMenuItem, clearResultsMenuItem }); var helpMenu = new System.Windows.Forms.ToolStripMenuItem("&Help"); aboutMenuItem = new System.Windows.Forms.ToolStripMenuItem("&About SQL Server Diagnostics...") { Name = "aboutMenuItem" }; helpMenu.DropDownItems.Add(aboutMenuItem); mainMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { connectionMenu, diagnosticsMenu, viewMenu, helpMenu }); mainMenu.Dock = System.Windows.Forms.DockStyle.Top;
            connectMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O; runSelectedMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F5; runHealthCheckMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F5; connectMenuItem.Click += ConnectClick; changeConnectionMenuItem.Click += ConnectClick; disconnectMenuItem.Click += DisconnectClick; runSelectedMenuItem.Click += RunSelectedClick; runHealthCheckMenuItem.Click += RunHealthCheckClick; cancelMenuItem.Click += CancelClick; refreshMenuItem.Click += RefreshClick; clearResultsMenuItem.Click += ClearResultsClick; aboutMenuItem.Click += AboutClick;
            toolStrip = new System.Windows.Forms.ToolStrip { Dock = System.Windows.Forms.DockStyle.Top, GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden }; connectToolButton = new System.Windows.Forms.ToolStripButton("Connect"); runToolButton = new System.Windows.Forms.ToolStripButton("Run Selected"); healthToolButton = new System.Windows.Forms.ToolStripButton("Health Check"); cancelToolButton = new System.Windows.Forms.ToolStripButton("Cancel"); toolStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { connectToolButton, new System.Windows.Forms.ToolStripSeparator(), runToolButton, healthToolButton, cancelToolButton }); connectToolButton.Click += ConnectClick; runToolButton.Click += RunSelectedClick; healthToolButton.Click += RunHealthCheckClick; cancelToolButton.Click += CancelClick;
            contextPanel = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Top, Height = 92, BackColor = System.Drawing.Color.FromArgb(31, 45, 61) }; var product = new System.Windows.Forms.Label { Text = "SQL Server Diagnostics", ForeColor = System.Drawing.Color.White, Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold), Location = new System.Drawing.Point(18, 12), AutoSize = true }; connectionStateLabel = new System.Windows.Forms.Label { Text = "DISCONNECTED", ForeColor = System.Drawing.Color.FromArgb(255, 205, 86), Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold), Location = new System.Drawing.Point(340, 24), AutoSize = true }; var serverCaption = new System.Windows.Forms.Label { Text = "Server", ForeColor = System.Drawing.Color.Silver, Location = new System.Drawing.Point(21, 58), AutoSize = true }; serverValueLabel = new System.Windows.Forms.Label { Text = "—", ForeColor = System.Drawing.Color.White, Location = new System.Drawing.Point(70, 58), AutoSize = true }; var databaseCaption = new System.Windows.Forms.Label { Text = "Database", ForeColor = System.Drawing.Color.Silver, Location = new System.Drawing.Point(280, 58), AutoSize = true }; databaseComboBox = new System.Windows.Forms.ComboBox { DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList, Location = new System.Drawing.Point(345, 54), Width = 210 }; databaseComboBox.SelectedIndexChanged += DatabaseChanged; versionValueLabel = new System.Windows.Forms.Label { ForeColor = System.Drawing.Color.White, Location = new System.Drawing.Point(575, 58), AutoSize = true }; refreshButton = new System.Windows.Forms.Button { Text = "Refresh", Location = new System.Drawing.Point(1168, 51), Size = new System.Drawing.Size(80, 28), Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right }; refreshButton.Click += RefreshClick; contextPanel.Controls.AddRange(new System.Windows.Forms.Control[] { product, connectionStateLabel, serverCaption, serverValueLabel, databaseCaption, databaseComboBox, versionValueLabel, refreshButton });
            workspaceSplit = new System.Windows.Forms.SplitContainer { Dock = System.Windows.Forms.DockStyle.Fill, FixedPanel = System.Windows.Forms.FixedPanel.Panel1, SplitterDistance = 180 }; workspaceSplit.Panel1.BackColor = System.Drawing.Color.FromArgb(240, 243, 247); navigationPanel = new System.Windows.Forms.FlowLayoutPanel { Dock = System.Windows.Forms.DockStyle.Fill, FlowDirection = System.Windows.Forms.FlowDirection.TopDown, WrapContents = false, Padding = new System.Windows.Forms.Padding(10, 16, 10, 10) }; allButton = CreateNavigationButton("Overview / All"); performanceButton = CreateNavigationButton("Performance"); indexesButton = CreateNavigationButton("Indexes"); integrityButton = CreateNavigationButton("Integrity"); schemaButton = CreateNavigationButton("Schema"); healthCheckButton = CreateNavigationButton("Health Check"); navigationPanel.Controls.AddRange(new System.Windows.Forms.Control[] { allButton, performanceButton, indexesButton, integrityButton, schemaButton, healthCheckButton }); workspaceSplit.Panel1.Controls.Add(navigationPanel); allButton.Click += delegate { ShowCategory(null); }; performanceButton.Click += delegate { ShowCategory(TheMaxLab.SqlServerDiagnostics.Core.Enums.DiagnosticCategory.Performance); }; indexesButton.Click += delegate { ShowCategory(TheMaxLab.SqlServerDiagnostics.Core.Enums.DiagnosticCategory.Indexes); }; integrityButton.Click += delegate { ShowCategory(TheMaxLab.SqlServerDiagnostics.Core.Enums.DiagnosticCategory.Integrity); }; schemaButton.Click += delegate { ShowCategory(TheMaxLab.SqlServerDiagnostics.Core.Enums.DiagnosticCategory.Schema); }; healthCheckButton.Click += delegate { workspaceTabs.SelectedTab = healthCheckTab; };
            workspaceTabs = new System.Windows.Forms.TabControl { Dock = System.Windows.Forms.DockStyle.Fill, Appearance = System.Windows.Forms.TabAppearance.FlatButtons, ItemSize = new System.Drawing.Size(0, 1), SizeMode = System.Windows.Forms.TabSizeMode.Fixed }; diagnosticsTab = new System.Windows.Forms.TabPage("Diagnostics"); healthCheckTab = new System.Windows.Forms.TabPage("Health Check"); workspaceTabs.TabPages.AddRange(new[] { diagnosticsTab, healthCheckTab }); workspaceSplit.Panel2.Controls.Add(workspaceTabs);
            diagnosticsSplit = new System.Windows.Forms.SplitContainer { Dock = System.Windows.Forms.DockStyle.Fill, SplitterDistance = 410 }; explorerHost = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Fill }; diagnosticsSplit.Panel1.Controls.Add(explorerHost); detailSplit = new System.Windows.Forms.SplitContainer { Dock = System.Windows.Forms.DockStyle.Fill, Orientation = System.Windows.Forms.Orientation.Horizontal, SplitterDistance = 265 }; detailsPanel = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Fill, Padding = new System.Windows.Forms.Padding(16) }; diagnosticNameLabel = new System.Windows.Forms.Label { Dock = System.Windows.Forms.DockStyle.Top, Height = 34, Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold), Text = "Select a diagnostic" }; diagnosticDescriptionTextBox = new System.Windows.Forms.TextBox { Dock = System.Windows.Forms.DockStyle.Top, Height = 48, Multiline = true, ReadOnly = true, BorderStyle = System.Windows.Forms.BorderStyle.None, BackColor = System.Drawing.Color.White }; metadataTable = new System.Windows.Forms.TableLayoutPanel { Dock = System.Windows.Forms.DockStyle.Fill, ColumnCount = 2, AutoScroll = true }; metadataTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 165)); metadataTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100)); runDiagnosticButton = new System.Windows.Forms.Button { Text = "Run Diagnostic", Size = new System.Drawing.Size(125, 32), Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right, Location = new System.Drawing.Point(620, 222) }; runDiagnosticButton.Click += RunSelectedClick; viewSqlButton = new System.Windows.Forms.Button { Text = "View SQL", Size = new System.Drawing.Size(95, 32), Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right, Location = new System.Drawing.Point(515, 222) }; viewSqlButton.Click += ViewSqlClick; detailsPanel.Controls.Add(metadataTable); detailsPanel.Controls.Add(diagnosticDescriptionTextBox); detailsPanel.Controls.Add(diagnosticNameLabel); detailsPanel.Controls.Add(viewSqlButton); detailsPanel.Controls.Add(runDiagnosticButton); resultHost = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Fill }; detailSplit.Panel1.Controls.Add(detailsPanel); detailSplit.Panel2.Controls.Add(resultHost); diagnosticsSplit.Panel2.Controls.Add(detailSplit); diagnosticsTab.Controls.Add(diagnosticsSplit);
            healthHeaderPanel = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Top, Height = 64, Padding = new System.Windows.Forms.Padding(12) }; healthSummaryLabel = new System.Windows.Forms.Label { Dock = System.Windows.Forms.DockStyle.Fill, Text = "Health Check has not been run.", Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold) }; healthProgressBar = new System.Windows.Forms.ProgressBar { Dock = System.Windows.Forms.DockStyle.Bottom, Height = 10 }; healthHeaderPanel.Controls.Add(healthSummaryLabel); healthHeaderPanel.Controls.Add(healthProgressBar); healthGrid = new System.Windows.Forms.DataGridView { Dock = System.Windows.Forms.DockStyle.Top, Height = 260, ReadOnly = true, AllowUserToAddRows = false, AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill, SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect, MultiSelect = false }; healthGrid.SelectionChanged += HealthResultSelected; healthResultHost = new System.Windows.Forms.Panel { Dock = System.Windows.Forms.DockStyle.Fill }; healthCheckTab.Controls.Add(healthResultHost); healthCheckTab.Controls.Add(healthGrid); healthCheckTab.Controls.Add(healthHeaderPanel);
            statusStrip = new System.Windows.Forms.StatusStrip(); connectionStatusLabel = new System.Windows.Forms.ToolStripStatusLabel("Disconnected"); diagnosticStatusLabel = new System.Windows.Forms.ToolStripStatusLabel("Diagnostic: none"); operationStatusLabel = new System.Windows.Forms.ToolStripStatusLabel("Ready"); durationStatusLabel = new System.Windows.Forms.ToolStripStatusLabel(); operationProgressBar = new System.Windows.Forms.ToolStripProgressBar { Style = System.Windows.Forms.ProgressBarStyle.Marquee, Visible = false }; statusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { connectionStatusLabel, new System.Windows.Forms.ToolStripStatusLabel { Spring = true }, diagnosticStatusLabel, operationStatusLabel, durationStatusLabel, operationProgressBar }); statusStrip.Dock = System.Windows.Forms.DockStyle.Bottom;
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi; ClientSize = new System.Drawing.Size(1280, 800); MinimumSize = new System.Drawing.Size(1000, 680); Font = new System.Drawing.Font("Segoe UI", 9F); MainMenuStrip = mainMenu; Text = "SQL Server Diagnostics"; StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen; Controls.Add(workspaceSplit); Controls.Add(contextPanel); Controls.Add(toolStrip); Controls.Add(mainMenu); Controls.Add(statusStrip); FormClosing += MainFormClosing; ResumeLayout(false); PerformLayout();
        }

        private static System.Windows.Forms.Button CreateNavigationButton(string text) { return new System.Windows.Forms.Button { Text = text, Width = 150, Height = 38, FlatStyle = System.Windows.Forms.FlatStyle.Flat, TextAlign = System.Drawing.ContentAlignment.MiddleLeft, Margin = new System.Windows.Forms.Padding(0, 0, 0, 6), TabStop = true }; }
    }
}