using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using TheMaxLab.SqlServerDiagnostics.App.Controls;
using TheMaxLab.SqlServerDiagnostics.App.Presentation;
using TheMaxLab.SqlServerDiagnostics.Core.Enums;
using TheMaxLab.SqlServerDiagnostics.Core.Interfaces;
using TheMaxLab.SqlServerDiagnostics.Core.Models;

namespace TheMaxLab.SqlServerDiagnostics.App.Forms
{
    public partial class MainForm : Form
    {
        private readonly IConnectionService connectionService; private readonly ISqlServerService sqlServerService; private readonly ICredentialService credentialService; private readonly IConnectionProfileService profileService; private readonly IDiagnosticEngine diagnosticEngine; private readonly IDiagnosticRepository diagnosticRepository; private readonly IDiagnosticInterpreter diagnosticInterpreter; private readonly IHealthScoreService healthScoreService; private readonly IReportService reportService; private readonly IExternalLinkLauncher externalLinkLauncher;
        private readonly DiagnosticExplorerControl explorer; private readonly DiagnosticResultViewerControl resultViewer; private readonly DiagnosticResultViewerControl healthResultViewer; private readonly HealthDashboardControl healthDashboard; private readonly TabPage dashboardTab; private readonly DiagnosticResultPresentation resultPresentation = new DiagnosticResultPresentation();
        private IReadOnlyList<DiagnosticDefinition> diagnostics = new List<DiagnosticDefinition>().AsReadOnly(); private DatabaseConnection currentConnection; private DiagnosticExecutionContext executionContext; private HealthReport currentHealthReport; private readonly HealthReportSession reportSession = new HealthReportSession(); private CancellationTokenSource executionCancellation; private bool suppressDatabaseChange; private readonly ToolStripMenuItem exportHtmlMenuItem = new ToolStripMenuItem("&HTML..."), exportJsonMenuItem = new ToolStripMenuItem("&JSON..."), exportFindingsCsvMenuItem = new ToolStripMenuItem("Findings &CSV..."), exportDiagnosticsCsvMenuItem = new ToolStripMenuItem("Diagnostics C&SV...");

        public MainForm(IConnectionService connectionService, ISqlServerService sqlServerService, ICredentialService credentialService, IConnectionProfileService profileService, IDiagnosticEngine diagnosticEngine, IDiagnosticRepository diagnosticRepository, IDiagnosticInterpreter diagnosticInterpreter, IHealthScoreService healthScoreService, IReportService reportService, IExternalLinkLauncher externalLinkLauncher)
        {
            this.connectionService = connectionService ?? throw new ArgumentNullException("connectionService"); this.sqlServerService = sqlServerService ?? throw new ArgumentNullException("sqlServerService"); this.credentialService = credentialService ?? throw new ArgumentNullException("credentialService"); this.profileService = profileService ?? throw new ArgumentNullException("profileService"); this.diagnosticEngine = diagnosticEngine ?? throw new ArgumentNullException("diagnosticEngine"); this.diagnosticRepository = diagnosticRepository ?? throw new ArgumentNullException("diagnosticRepository"); this.diagnosticInterpreter = diagnosticInterpreter ?? throw new ArgumentNullException("diagnosticInterpreter"); this.healthScoreService = healthScoreService ?? throw new ArgumentNullException("healthScoreService"); this.reportService = reportService ?? throw new ArgumentNullException("reportService"); this.externalLinkLauncher = externalLinkLauncher ?? throw new ArgumentNullException("externalLinkLauncher");
            InitializeComponent(); AddExportMenu(); explorer = new DiagnosticExplorerControl(new DiagnosticExplorerPresentation()); explorer.SelectedDiagnosticChanged += DiagnosticSelected; explorerHost.Controls.Add(explorer); resultViewer = new DiagnosticResultViewerControl(resultPresentation); resultHost.Controls.Add(resultViewer); healthResultViewer = new DiagnosticResultViewerControl(resultPresentation); healthResultHost.Controls.Add(healthResultViewer); healthDashboard = new HealthDashboardControl(); dashboardTab = new TabPage("Dashboard"); dashboardTab.Controls.Add(healthDashboard); workspaceTabs.TabPages.Insert(0, dashboardTab); allButton.Click += delegate { workspaceTabs.SelectedTab = dashboardTab; }; healthGrid.Columns.Add("Diagnostic", "Diagnostic"); healthGrid.Columns.Add("Status", "Status"); healthGrid.Columns.Add("Duration", "Duration"); Shown += MainFormShown; UpdateCommandState();
        }

        private async void MainFormShown(object sender, EventArgs e) { try { await ReloadDiagnosticsAsync(); } catch (Exception) { MessageBox.Show(this, "The diagnostic catalog could not be loaded. Verify the diagnostics directory and manifest.", "Diagnostic catalog", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
        private async void ConnectClick(object sender, EventArgs e) { if (executionCancellation != null) return; using (var form = new ConnectionForm(connectionService, sqlServerService, credentialService, profileService, currentConnection)) { if (form.ShowDialog(this) != DialogResult.OK) return; ApplyConnection(form.SelectedConnection, form.ConnectionResult); await RefreshDatabasesAsync(form.SelectedConnection.DatabaseName); } }
        private void ApplyConnection(DatabaseConnection connection, ConnectionTestResult test) { currentConnection = connection; executionContext = new DiagnosticExecutionContext { Connection = connection, Server = test.Server, Database = test.Database }; connectionStateLabel.Text = "CONNECTED"; connectionStateLabel.ForeColor = Color.FromArgb(92, 184, 92); serverValueLabel.Text = test.Server.ServerName; versionValueLabel.Text = string.Format("SQL Server {0} · {1}", test.Server.ProductVersion, test.Server.Edition); connectionStatusLabel.Text = "Connected: " + test.Server.ServerName + " / " + test.Database.Name; ClearResults(); UpdateCommandState(); }
        private async Task RefreshDatabasesAsync(string selectedDatabase) { if (currentConnection == null) return; try { suppressDatabaseChange = true; var databases = await sqlServerService.GetDatabasesAsync(currentConnection, CancellationToken.None); databaseComboBox.Items.Clear(); databaseComboBox.Items.AddRange(databases.Select(item => item.Name).Cast<object>().ToArray()); databaseComboBox.SelectedItem = selectedDatabase; if (databaseComboBox.SelectedIndex < 0 && databaseComboBox.Items.Count > 0) databaseComboBox.SelectedIndex = 0; } catch (Exception) { operationStatusLabel.Text = "Database refresh failed"; } finally { suppressDatabaseChange = false; } }
        private async void DatabaseChanged(object sender, EventArgs e) { if (suppressDatabaseChange || currentConnection == null || databaseComboBox.SelectedItem == null || executionCancellation != null) return; try { DatabaseConnection candidate = CloneConnection(currentConnection, Convert.ToString(databaseComboBox.SelectedItem)); DatabaseInfo database = await sqlServerService.GetDatabaseInfoAsync(candidate, CancellationToken.None); currentConnection = candidate; executionContext = new DiagnosticExecutionContext { Connection = candidate, Server = executionContext.Server, Database = database }; connectionStatusLabel.Text = "Connected: " + executionContext.Server.ServerName + " / " + database.Name; ClearResults(); operationStatusLabel.Text = "Database changed; previous results cleared"; } catch (Exception) { suppressDatabaseChange = true; databaseComboBox.SelectedItem = currentConnection.DatabaseName; suppressDatabaseChange = false; operationStatusLabel.Text = "Database change failed; previous database remains active"; } }
        private void DisconnectClick(object sender, EventArgs e) { if (executionCancellation != null) executionCancellation.Cancel(); currentConnection = null; executionContext = null; suppressDatabaseChange = true; databaseComboBox.Items.Clear(); suppressDatabaseChange = false; serverValueLabel.Text = "—"; versionValueLabel.Text = string.Empty; connectionStateLabel.Text = "DISCONNECTED"; connectionStateLabel.ForeColor = Color.FromArgb(255, 205, 86); connectionStatusLabel.Text = "Disconnected"; ClearResults(); UpdateCommandState(); }
        private async void RefreshClick(object sender, EventArgs e) { try { if (currentConnection == null) { await ReloadDiagnosticsAsync(); return; } ConnectionTestResult test = await connectionService.TestAsync(currentConnection, CancellationToken.None); if (!test.Success) { operationStatusLabel.Text = test.Message; return; } ApplyConnection(currentConnection, test); await RefreshDatabasesAsync(currentConnection.DatabaseName); await ReloadDiagnosticsAsync(); } catch (Exception) { operationStatusLabel.Text = "Refresh failed"; } }
        private async Task ReloadDiagnosticsAsync() { diagnostics = await diagnosticEngine.GetDiagnosticsAsync(CancellationToken.None); explorer.SetDiagnostics(diagnostics); UpdateNavigationCounts(); }
        private void ShowCategory(DiagnosticCategory? category) { workspaceTabs.SelectedTab = diagnosticsTab; explorer.SelectCategory(category); }
        private void DiagnosticSelected(object sender, EventArgs e) { DiagnosticDefinition definition = explorer.SelectedDiagnostic; metadataTable.Controls.Clear(); metadataTable.RowStyles.Clear(); metadataTable.RowCount = 0; if (definition == null) { diagnosticNameLabel.Text = "Select a diagnostic"; diagnosticDescriptionTextBox.Text = string.Empty; UpdateCommandState(); return; } diagnosticNameLabel.Text = definition.Name; diagnosticDescriptionTextBox.Text = definition.Description; AddMetadata("Category", definition.Category.ToString()); AddMetadata("Tags", string.Join(", ", definition.Tags)); AddMetadata("Execution cost", definition.ExecutionCost.ToString()); AddMetadata("Execution scope", definition.ExecutionScope.ToString()); AddMetadata("SQL Server versions", definition.MinimumSqlServerVersion + "+" + (string.IsNullOrWhiteSpace(definition.MaximumSqlServerVersion) ? string.Empty : " through " + definition.MaximumSqlServerVersion)); AddMetadata("Required permissions", string.Join("; ", definition.RequiredPermissions)); AddMetadata("Query Store", definition.RequiresQueryStore ? "Required" : "Not required"); AddMetadata("Azure SQL", definition.SupportsAzureSql ? "Declared supported" : "Not supported"); AddMetadata("Multiple result sets", definition.MultipleResultSets ? "Yes" : "No"); AddMetadata("Health Check", definition.HealthCheckEnabled ? "Eligible when compatible" : "Manual only"); AddMetadata("Interpretation", definition.ResultInterpretation.Mode.ToString()); AddMetadata("Empty result", definition.ResultInterpretation.EmptyResultMeaning.ToString()); AddMetadata("Impact / confidence", definition.ResultInterpretation.Impact + " / " + definition.ResultInterpretation.Confidence); AddMetadata("Health Score", definition.ScorePolicy.ScoreEligible ? "Eligible; weight " + definition.ScorePolicy.Weight.ToString("0.##") : "Excluded"); AddMetadata("Timeout", definition.TimeoutSeconds + " seconds"); AddMetadata("Source", definition.ScriptPath); diagnosticStatusLabel.Text = "Diagnostic: " + definition.Name; UpdateCommandState(); }
        private void AddMetadata(string name, string value) { int row = metadataTable.RowCount++; metadataTable.RowStyles.Add(new RowStyle(SizeType.AutoSize)); metadataTable.Controls.Add(new Label { Text = name, Font = new Font(Font, FontStyle.Bold), AutoSize = true, Margin = new Padding(0, 3, 8, 3) }, 0, row); metadataTable.Controls.Add(new Label { Text = string.IsNullOrWhiteSpace(value) ? "—" : value, AutoSize = true, MaximumSize = new Size(550, 0), Margin = new Padding(0, 3, 0, 3) }, 1, row); }
        private async void ViewSqlClick(object sender, EventArgs e) { DiagnosticDefinition definition = explorer.SelectedDiagnostic; if (definition == null) return; try { string sql = await diagnosticRepository.LoadScriptAsync(definition, CancellationToken.None); using (var viewer = new SqlViewerForm(definition.Name + " — SQL Source", definition.ScriptPath, sql)) viewer.ShowDialog(this); } catch (Exception) { MessageBox.Show(this, "The diagnostic SQL source could not be loaded.", "SQL source", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
        private async void RunSelectedClick(object sender, EventArgs e) { DiagnosticDefinition definition = explorer.SelectedDiagnostic; if (definition == null || executionContext == null || executionCancellation != null) return; BeginOperation("Running", definition.Name, false); try { DiagnosticResult result = await diagnosticEngine.ExecuteAsync(definition, executionContext, executionCancellation.Token); resultViewer.ShowResult(result); operationStatusLabel.Text = resultPresentation.GetDisplayStatus(result); durationStatusLabel.Text = result.Duration.TotalSeconds.ToString("0.00") + "s"; } catch (OperationCanceledException) { operationStatusLabel.Text = "Cancelled"; } catch (Exception) { operationStatusLabel.Text = "Unable to run diagnostic"; } finally { EndOperation(); } }
        private async void RunHealthCheckClick(object sender, EventArgs e) { if (executionContext == null || executionCancellation != null) return; currentHealthReport = null; reportSession.Clear(); healthDashboard.ClearReport(); UpdateCommandState(); workspaceTabs.SelectedTab = healthCheckTab; healthGrid.Rows.Clear(); healthResultViewer.ClearResults(); BeginOperation("Running Health Check", string.Empty, true); try { int selected = (await diagnosticEngine.GetHealthCheckCandidatesAsync(executionContext, executionCancellation.Token)).Count; healthSummaryLabel.Text = string.Format("Diagnostics selected: {0} · Starting...", selected); healthProgressBar.Maximum = Math.Max(1, selected); healthProgressBar.Value = 0; var progress = new Progress<DiagnosticProgress>(item => { healthProgressBar.Value = Math.Min(healthProgressBar.Maximum, item.Completed); healthSummaryLabel.Text = string.Format("{0}: {1} · Completed {2} / {3}", item.Stage, item.CurrentDiagnosticName, item.Completed, item.Total); diagnosticStatusLabel.Text = "Diagnostic: " + item.CurrentDiagnosticName; }); HealthCheckReport report = await diagnosticEngine.RunHealthCheckAsync(executionContext, progress, executionCancellation.Token); PopulateHealthReport(report, selected); if (executionCancellation.IsCancellationRequested) { currentHealthReport = null; healthDashboard.ClearReport(); operationStatusLabel.Text = "Cancelled"; return; } var map = diagnostics.ToDictionary(x => x.Id, StringComparer.OrdinalIgnoreCase); var interpretations = report.Results.Where(x => map.ContainsKey(x.DiagnosticId)).Select(x => diagnosticInterpreter.Interpret(map[x.DiagnosticId], x)).ToList(); currentHealthReport = healthScoreService.BuildReport(report, diagnostics, interpretations); reportSession.Set(currentHealthReport, executionContext); report.Score = currentHealthReport.HealthScore; healthDashboard.ShowReport(currentHealthReport); workspaceTabs.SelectedTab = dashboardTab; operationStatusLabel.Text = "Completed"; durationStatusLabel.Text = report.Duration.TotalSeconds.ToString("0.00") + "s"; } catch (OperationCanceledException) { currentHealthReport = null; operationStatusLabel.Text = "Cancelled"; } catch (Exception) { currentHealthReport = null; operationStatusLabel.Text = "Health Check failed to start"; } finally { EndOperation(); } }
        private void PopulateHealthReport(HealthCheckReport report, int selected) { healthGrid.Rows.Clear(); foreach (DiagnosticResult result in report.Results) { int index = healthGrid.Rows.Add(result.DiagnosticName, resultPresentation.GetDisplayStatus(result), result.Duration.TotalSeconds.ToString("0.00") + "s"); healthGrid.Rows[index].Tag = result; } HealthCheckSummary summary = HealthCheckSummary.FromReport(report, selected); healthSummaryLabel.Text = string.Format("Selected: {0}   Completed: {1}   Critical: {2}   Warnings: {3}   Information: {4}   Skipped: {5}   Failed: {6}   Cancelled: {7}", summary.Selected, summary.Completed, summary.Critical, summary.Warnings, summary.Information, summary.Skipped, summary.Failed, summary.Cancelled); if (healthGrid.Rows.Count > 0) healthGrid.Rows[0].Selected = true; }
        private void HealthResultSelected(object sender, EventArgs e) { if (healthGrid.SelectedRows.Count > 0) healthResultViewer.ShowResult(healthGrid.SelectedRows[0].Tag as DiagnosticResult); }
        private void CancelClick(object sender, EventArgs e) { if (executionCancellation != null) { operationStatusLabel.Text = "Cancelling..."; executionCancellation.Cancel(); } }
        private void ClearResultsClick(object sender, EventArgs e) { ClearResults(); }
        private void AboutClick(object sender, EventArgs e) { using (var form = new AboutForm(externalLinkLauncher)) form.ShowDialog(this); }
        private void ClearResults() { currentHealthReport = null; reportSession.Clear(); resultViewer.ClearResults(); healthResultViewer.ClearResults(); healthDashboard.ClearReport(); healthGrid.Rows.Clear(); healthSummaryLabel.Text = "Health Check has not been run."; durationStatusLabel.Text = string.Empty; operationStatusLabel.Text = "Ready"; UpdateCommandState(); }
        private void BeginOperation(string status, string diagnostic, bool determinate) { executionCancellation = new CancellationTokenSource(); operationStatusLabel.Text = status; if (!string.IsNullOrEmpty(diagnostic)) diagnosticStatusLabel.Text = "Diagnostic: " + diagnostic; operationProgressBar.Visible = !determinate; UpdateCommandState(); }
        private void EndOperation() { operationProgressBar.Visible = false; executionCancellation.Dispose(); executionCancellation = null; UpdateCommandState(); }
        private void UpdateCommandState() { bool connected = executionContext != null; bool running = executionCancellation != null; bool selected = explorer != null && explorer.SelectedDiagnostic != null; bool canExport = connected && reportSession.GetFor(executionContext) != null && !running; runDiagnosticButton.Enabled = connected && selected && !running; runToolButton.Enabled = connected && selected && !running; runSelectedMenuItem.Enabled = connected && selected && !running; viewSqlButton.Enabled = selected && !running; healthToolButton.Enabled = connected && !running; healthCheckButton.Enabled = connected && !running; runHealthCheckMenuItem.Enabled = connected && !running; cancelToolButton.Enabled = running; cancelMenuItem.Enabled = running; disconnectMenuItem.Enabled = connected && !running; changeConnectionMenuItem.Enabled = !running; databaseComboBox.Enabled = connected && !running; refreshButton.Enabled = !running; exportHtmlMenuItem.Enabled = canExport; exportJsonMenuItem.Enabled = canExport; exportFindingsCsvMenuItem.Enabled = canExport; exportDiagnosticsCsvMenuItem.Enabled = canExport; }

        private void AddExportMenu()
        {
            var file = new ToolStripMenuItem("&File"); var export = new ToolStripMenuItem("Export Health &Report"); export.DropDownItems.AddRange(new ToolStripItem[] { exportHtmlMenuItem, exportJsonMenuItem, new ToolStripSeparator(), exportFindingsCsvMenuItem, exportDiagnosticsCsvMenuItem }); file.DropDownItems.Add(export); mainMenu.Items.Insert(0, file);
            exportHtmlMenuItem.Click += async delegate { await ExportReportAsync("html"); }; exportJsonMenuItem.Click += async delegate { await ExportReportAsync("json"); }; exportFindingsCsvMenuItem.Click += async delegate { await ExportReportAsync("findings.csv"); }; exportDiagnosticsCsvMenuItem.Click += async delegate { await ExportReportAsync("diagnostics.csv"); };
        }

        private async Task ExportReportAsync(string format)
        {
            HealthReport report = reportSession.GetFor(executionContext);
            if (report == null || executionCancellation != null) return;
            string extension = format.EndsWith("csv", StringComparison.OrdinalIgnoreCase) ? "csv" : format; using (var dialog = new SaveFileDialog { AddExtension = true, DefaultExt = extension, FileName = reportService.CreateSafeFileName(report, extension), Filter = extension == "html" ? "HTML report (*.html)|*.html" : extension == "json" ? "JSON report (*.json)|*.json" : "CSV file (*.csv)|*.csv" })
            {
                if (dialog.ShowDialog(this) != DialogResult.OK) return; BeginOperation("Generating report", string.Empty, false);
                try { var options = new ReportOptions(); if (format == "html") await reportService.ExportHtmlAsync(report, options, dialog.FileName, executionCancellation.Token); else if (format == "json") await reportService.ExportJsonAsync(report, options, dialog.FileName, executionCancellation.Token); else if (format == "findings.csv") await reportService.ExportFindingsCsvAsync(report, options, dialog.FileName, executionCancellation.Token); else await reportService.ExportDiagnosticsCsvAsync(report, options, dialog.FileName, executionCancellation.Token); operationStatusLabel.Text = "Report exported"; }
                catch (OperationCanceledException) { operationStatusLabel.Text = "Report export cancelled"; }
                catch (Exception) { operationStatusLabel.Text = "Report export failed"; MessageBox.Show(this, "The report could not be generated or written. Verify the destination and try again.", "Report export", MessageBoxButtons.OK, MessageBoxIcon.Warning); }
                finally { EndOperation(); }
            }
        }
        private void UpdateNavigationCounts() { var counts = new DiagnosticExplorerPresentation().GetCategoryCounts(diagnostics); allButton.Text = "Overview / All (" + diagnostics.Count + ")"; performanceButton.Text = "Performance (" + counts[DiagnosticCategory.Performance] + ")"; indexesButton.Text = "Indexes (" + counts[DiagnosticCategory.Indexes] + ")"; integrityButton.Text = "Integrity (" + counts[DiagnosticCategory.Integrity] + ")"; schemaButton.Text = "Schema (" + counts[DiagnosticCategory.Schema] + ")"; healthCheckButton.Text = "Health Check (" + diagnostics.Count(item => item.HealthCheckEnabled) + ")"; }
        private void MainFormClosing(object sender, FormClosingEventArgs e) { if (executionCancellation != null) executionCancellation.Cancel(); }
        protected override bool ProcessCmdKey(ref Message message, Keys keyData) { if (keyData == Keys.Escape && executionCancellation != null) { CancelClick(this, EventArgs.Empty); return true; } return base.ProcessCmdKey(ref message, keyData); }
        private static DatabaseConnection CloneConnection(DatabaseConnection source, string database) { return new DatabaseConnection { ServerName = source.ServerName, DatabaseName = database, AuthenticationType = source.AuthenticationType, UserName = source.UserName, CredentialKey = source.CredentialKey, Encrypt = source.Encrypt, TrustServerCertificate = source.TrustServerCertificate, ConnectionTimeoutSeconds = source.ConnectionTimeoutSeconds }; }
    }
}